apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: app
          image: pskaletskyy/build_ship_run_app:v1
          ports:
            - containerPort: 8080